### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by felipesilva-hotmart** [SonarSource/sonarqube-quality-gate-action#10]
This action only works on linux due to it using a docker container.
Would be good if this action could work for Mac OSX and Windows too, but I guess this would mean moving away from a docker implementation.
At very least (although does not work for me) call this out in the README that only Linux is supported.

<img width="1364" alt="Captura de Tela 2021-11-19 às 13 47 30" src="https://user-images.githubusercontent.com/89803606/142660752-4d0ac5e7-3844-48c9-9115-0da7ce4807e9.png">

**Comment by tobias-trabelsi-sonarsource** [comment]
Hello there :wave: 

you opened the ticket in the wrong repository. This is the quality gate action (which is not running in a container btw) and in your snippet you are referencing the scan action.
There is already a open issue that asks for a JS based action (https://github.com/SonarSource/sonarqube-scan-action/issues/13) and not a containerized based one. i guess that would also solve your concerns.
