### ISSUE TITLE
Possible to allow SONAR_HOST_URL to be respected

### ISSUE THREAD

**Issue by erikhjensen** [SonarSource/sonarqube-quality-gate-action#16]
The Quality Gate action doesn't seem to support the SONAR_HOST_URL and seemingly wants to get the sonarhost from inside the scan results.

In our case, sonarqube has a friendly dns name on our corporate domain but it also has an internet-resolvable name that the containerized actions can use to resolve and interact.  In the case of the scan-action, this less friendly hostname is what's used for SONAR_HOST_URL... but because the sonarqube instance's base-url is the friendly dns-name.. the quality gate action seems to want to resolve the friendly name which it cant.. even through it may be running on a private LAN runner and it doesn't seem to use the host's dns to resolve the sonarqube location.    So in light of this tendency for the quality gate action to resolve the sonar_host in a different way that the scan-action, could we allow it to look for SONAR_HOST_URL and if present, use that in lieu of the url from the scan results?

https://github.com/SonarSource/sonarqube-quality-gate-action/blob/master/script/check-quality-gate.sh#L17 - where the host is extracted from the file

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @erikhjensen . Thanks for your suggestion. I've opened a ticket [here](https://jira.sonarsource.com/browse/SQQGGHA-1). You can track progress over there.
