### ISSUE TITLE
Comment on Pull request like SonarCloud

### ISSUE THREAD

**Issue by rosspatil** [SonarSource/sonarqube-quality-gate-action#19]
SonarCloud comments on the result of the Pull request once the quality gate scan is done. But for that we need an onboard repository in sonarCloud. It doesn't work for manually created projects.

So what if I extend this quality gate action to also comment on the report on pull requests that is also configurable based on parameters?

The other option is to have one GitHub action to perform this. I have written my GitHub action to perform this operation in case we want to take that project under  SonarSource.

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @rosspatil.

This is not tied to the GitHub Action, but to your SonarQube configuration. SonarQube Developer Edition (and above) will decorate your pull requests with the quality gate status, exactly like SonarCloud does (it's basically the same technical feature). This is triggered by an analysis, which you can run using our other GitHub Action ([sonarqube-scan-action](https://github.com/SonarSource/sonarqube-scan-action)), or by executing one of our [scanners](https://docs.sonarqube.org/latest/analysis/overview/) directly.

You can read more about pull request decoration [here](https://docs.sonarqube.org/latest/analysis/github-integration/).
