### ISSUE TITLE
End workflow when quality gate result is Error

### ISSUE THREAD

**Issue by jun-jia** [SonarSource/sonarqube-quality-gate-action#20]
hello, 

When I get the Error result from quality gate, the workflow still ends successfully. How could I failed the workflow if the quality gate result is "ERROR"?

**Comment by Guerlielton** [comment]
![Screenshot from 2022-08-20 00-02-14](https://user-images.githubusercontent.com/1194670/185726538-ab30212a-74ee-4ace-9fb5-cb1f7f541bb7.png)

Hi @jun-jia  when, I received this is warning and was broken my pipeline

**Comment by wouter-admiraal-sonarsource** [comment]
I don't see any issue here. I'm closing this thread, but feel free to re-open it if you're still experiencing problems, @jun-jia .
