### ISSUE TITLE
`set-output` is deprecated.  Prefer using environment files

### ISSUE THREAD

**Issue by poconnor-lab49** [SonarSource/sonarqube-quality-gate-action#29]
From the [Github blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) on 2022-10-11

> Action and workflow authors who are using `save-state` or `set-output` via stdout should update to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).

**Comment by wouter-admiraal-sonarsource** [comment]
Thanks for your contribution, @poconnor-lab49 . PR #30 approved.
