### ISSUE TITLE
master version: line 46: ${GITHUB_OUTPUT}: ambiguous redirect

### ISSUE THREAD

**Issue by macaranduba** [SonarSource/sonarqube-quality-gate-action#32]
Hi!
After the last commit 745e48ebda7ca739977f8fcd7ab61f1066b58bd3, the following started to happening:

/home/runner/actions-runner/_work/_actions/sonarsource/sonarqube-quality-gate-action/master/script/check-quality-gate.sh: line 46: ${GITHUB_OUTPUT}: ambiguous redirect

Any thoughts on how to overcome this?
Thank you in advance.

**Comment by mhutzsch** [comment]
+1 went back to the HEAD~1

**Comment by poconnor-lab49** [comment]
Can you add some more detail?  Is this on a hosted runner for instance?

Looks like this might be the solution, but it doesn't explain why: https://github.com/community/community/discussions/36746

**Comment by poconnor-lab49** [comment]
Assuming you have a space somewhere in your GITHUB_OUTPUT maybe, can you try my fix branch please?

```
uses: poconnor-lab49/sonarqube-quality-gate-action@bug/amiguous-redirect
```

**Comment by mhutzsch** [comment]
I haven't tried your branch so far, but the fix is not implementing the suggested solution in the link. Is this intended

**Comment by macaranduba** [comment]
Hi @poconnor-lab49 ,
I'm using using hosted runner. I don't set or event see a GITHUB_OUTPUT property defined on my environment.
The poconnor-lab49/sonarqube-quality-gate-action@bug/amiguous-redirect fix did the trick.
Thanks for a so quick response!

**Comment by poconnor-lab49** [comment]
> I haven't tried your branch so far, but the fix is not implementing the suggested solution in the link. Is this intended

Yes.  Ambiguous redirect could be lots of things, but after thinking about it for a minute I figured it might be special characters or spaces in the in the ${GITHUB_OUTPUT} env var.  I've added a test that reproduces the problem and it sounds like the fix works, so if you can confirm @mhutzsch I'll open a new PR.

Sorry about the trouble!

**Comment by poconnor-lab49** [comment]
> I haven't tried your branch so far, but the fix is not implementing the suggested solution in the link. Is this intended

Yes.  Unfortunately "ambiguous redirect" could be lots of stuff.  I realized I hadn't quoted the ${GITHUB_OUTPUT} env var and that could be causing some problems, so thought we could start there.

**Comment by macaranduba** [comment]
No, i'm not running a self hosted runner. Should I defined the GITHUB_OUTPUT variable?

**Comment by poconnor-lab49** [comment]
> No, i'm not running a self hosted runner. Should I defined the GITHUB_OUTPUT variable?

You __really__ shouldn't have to. Can you share a reproducer?

**Comment by macaranduba** [comment]
Sorry, I don't think I can share a reproducer.

The result of the print was 
"GITHUB_OUTPUT is "

One way to reproduce it would be removing that variable all together, but don't know if it make sense at all.

**Comment by macaranduba** [comment]
Yep, if GITHUB_OUTPUT is not defined, there will no file to write the echo right?

**Comment by poconnor-lab49** [comment]
> Sorry, I don't think I can share a reproducer.

No problem.

> 
> The result of the print was "GITHUB_OUTPUT is "
> 
> One way to reproduce it would be removing that variable all together, but don't know if it make sense at all.

AFAIK, `GITHUB_OUTPUT` should _not_ be empty.  Can you start a discussion in [Github Community](https://github.com/orgs/community/discussions) and add a link to it here please?

Out of curiousity, are you setting `runs_on` to something besides [one of the supported images](https://github.com/actions/runner-images#available-images) ?  Maybe Github has not ported GITHUB_OUTPUT to some runners?

If that's the case I don't know what the right thing to do here is.  Maybe create a new branch for the environment variable changes and revert master to `HEAD~1`: 00d36147d53bcfcc3ba5bde52e55d0783f829f8b

**Comment by macaranduba** [comment]
Yep, certenatly that's why: we are running organization's runners.
Thanks and sorry for the trouble!

**Comment by macaranduba** [comment]
I tried to provide the GITHUB property, before calling the sonar one, like this
echo "GITHUB_OUTPUT=/dev/stdout" >> $GITHUB_ENV
and it seems to worked for linux based runners.

Thank you all and specially @poconnor-lab49

**Comment by poconnor-lab49** [comment]
@macaranduba I pushed a change to my branch based on this comment to fall back to `set-output`: https://github.com/nektos/act/issues/1386#issuecomment-1277840901

Would you mind retrying using my branch and without explicitly setting the GITHUB_OUTPUT?  If the fallback works, I'll open another PR.

**Comment by macaranduba** [comment]
It worked like a charm @poconnor-lab49!
Thank you!

**Comment by poconnor-lab49** [comment]
Good news!  Opened the PR here: https://github.com/SonarSource/sonarqube-quality-gate-action/pull/33
