### ISSUE TITLE
Self-signed certificates for SonarQube Server

### ISSUE THREAD

**Issue by miguel-oltra** [SonarSource/sonarqube-quality-gate-action#34]
When using self-signed certificate this GH action will require to get a similar configuration variable than the issue fixed in sonar-scan-action [https://github.com/SonarSource/sonarqube-scan-action/commit/50d5d981633b1b78cd3bc540ec4a7e18bb295ee5](url).

A variable such as: SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }} should be enabled by modifying the script/check-quality-gate.sh file such in the sister action.

Otherwise you will experience an error such as:

![image](https://user-images.githubusercontent.com/39242642/200888808-045c1125-beca-4927-97d5-acb7d504403f.png)

**Comment by bdzanko17** [comment]
This is also resolved in https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/bin/entrypoint.sh

I have this issue.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/41085720/205598151-cab8db73-4afa-444f-924d-85ee396f03be.png">

**Comment by dja557** [comment]
Yes, please add this ability. This is a great inconvenience!

**Comment by yibble** [comment]
This PR should resolve the issue: https://github.com/SonarSource/sonarqube-quality-gate-action/pull/39

**Comment by jacek-poreda-sonarsource** [comment]
As @yibble wrote, this issue has been resolved. Closing.
