### ISSUE TITLE
Running `on:workflow_dispatch:` using a branch will make sonarqube think it's `main`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [SonarSource/sonarqube-quality-gate-action#35]
Hi,

I wanted to get a sonarqube report of a stale branch so I selected it using this:
![image](https://user-images.githubusercontent.com/5499778/201895802-c5125004-9529-4877-acc4-05f98dae2363.png)
However, instead of getting a new branch in SonarCloud, I got a worse rating in my `main` branch.

Is there a way to help the scanner understand that I'm referencing a branch here?

**Comment by philippe-perrin-sonarsource** [comment]
Hello, everyone, and thanks for your feedback.

As you might have realized by now, we are not actively monitoring issues created on this repository. This is a mistake on our side, and this capability should have been disabled on this repository in the first place.

Instead, if you are still encountering issues, please provide us with feedback on [our community forum](https://community.sonarsource.com/), which is actively monitored.
