### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by remoteexception** [SonarSource/sonarqube-quality-gate-action#37]
Hi, can you create a new Release Tag please? Otherwise I have to point this action to master in my pipeline to have the latest fixes, what is a bit risky. Thanks a lot! Kind regards, Jana

**Comment by philippe-perrin-sonarsource** [comment]
Hello, everyone, and thanks for your feedback.

As you might have realized by now, we are not actively monitoring issues created on this repository. This is a mistake on our side, and this capability should have been disabled on this repository in the first place.

Instead, if you are still encountering issues, please provide us with feedback on [our community forum](https://community.sonarsource.com/), which is actively monitored.
