### ISSUE TITLE
Problem with getting output variable "quality-gate-status" from example YAML quality check.

### ISSUE THREAD

**Issue by bieli** [SonarSource/sonarqube-quality-gate-action#38]
On my repository, I can't see the variable declared in documentation `outputs.quality-gate-status`:
```yaml
${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}
```
What I can see, it's an error like this: https://github.com/bieli/FreeItLessons/actions/runs/4212407576/workflow in my CI:
```bash
Check failure on line 39 in .github/workflows/sonarqube-quality-check.yaml

GitHub Actions
/ .github/workflows/sonarqube-quality-check.yaml
Invalid workflow file
You have an error in your yaml syntax on line 39
```

This is my copy/paste YAML Sonar quality gate check:
https://github.com/bieli/FreeItLessons/blob/master/.github/workflows/sonarqube-quality-check.yaml

Maybe you have any suggestions?

**Comment by philippe-perrin-sonarsource** [comment]
Hello, everyone, and thanks for your feedback.

As you might have realized by now, we are not actively monitoring issues created on this repository. This is a mistake on our side, and this capability should have been disabled on this repository in the first place.

Instead, if you are still encountering issues, please provide us with feedback on [our community forum](https://community.sonarsource.com/), which is actively monitored.
