### ISSUE TITLE
Quality gate check returns 404

### ISSUE THREAD

**Issue by tyagiprince2010** [SonarSource/sonarqube-quality-gate-action#46]
I have a workflow which looks like this!
<img width="462" alt="Screenshot 2023-08-27 at 4 51 36 PM" src="https://github.com/SonarSource/sonarqube-quality-gate-action/assets/42529112/ea6a18da-803c-477a-ba5d-57e79afcbf0c">

The scan runs successfully but the workflow fails at quality-gate check step. Below is the error. 
<img width="819" alt="Screenshot 2023-08-27 at 4 50 28 PM" src="https://github.com/SonarSource/sonarqube-quality-gate-action/assets/42529112/adf37787-3257-4254-ae0f-521ecfd7e84e">

Tried adding/removing projectBaseDir and other args, but no luck. Is this a known issue or am i missing something in the workflow?

**Comment by gvidaspr** [comment]
@tyagiprince2010 Having the same issue - did you manage to solve this?

**Comment by esteban-go** [comment]
hello, is there any progress on this? my team is having the same issue
We are calling the action with the SONAR_TOKEN and SONAR_HOST_URL?

**Comment by Debjit-Roy** [comment]
We are also using the same steps and facing the same issue. Request a quick resolution.

**Comment by esteban-go** [comment]
> hello, is there any progress on this? my team is having the same issue We are calling the action with the SONAR_TOKEN and SONAR_HOST_URL?

The root error come from the sonar server, it seems we need to update the server to 10.2.1 version. More details about the error:  https://community.sonarsource.com/t/background-tasks-for-project-analysis-on-master-branch-fail-with-npe/96502

**Comment by HoangNguyen211** [comment]
I faced the same issue in Sonar Enterprise Edition - Version 10.4.1.
The gate is checking "analysisId":
![image](https://github.com/SonarSource/sonarqube-quality-gate-action/assets/49058793/a236ed29-0d3c-41ba-bd13-ac49ab38ea2a)
But in output of curl command, it is not there so we got 404:
![image](https://github.com/SonarSource/sonarqube-quality-gate-action/assets/49058793/3ffcc710-002b-4689-9c50-e5f0e0219319)
Please suggest.

**Comment by jacek-poreda-sonarsource** [comment]
@HoangNguyen211 Do you still experience the issue with latest SQ version?

**Comment by rkdeloitted** [comment]
Was it resolved ? We are checking out this repo from our actions for sonarcloud still facing the same issue .

**Comment by shankarRaman** [comment]
We are also experiencing the same issue when using version 10.7.0. Any suggestion on how to resolve this?

**Comment by philippe-perrin-sonarsource** [comment]
Hello, everyone, and thanks for your feedback.

As you might have realized by now, we are not actively monitoring issues created on this repository. This is a mistake on our side, and this capability should have been disabled on this repository in the first place.

Instead, if you are still encountering issues, please provide us with feedback on [our community forum](https://community.sonarsource.com/), which is actively monitored.

**Comment by philippe-perrin-sonarsource** [comment]
Hello, everyone, and thanks for your feedback.

As you might have realized by now, we are not actively monitoring issues created on this repository. This is a mistake on our side, and this capability should have been disabled on this repository in the first place.

Instead, if you are still encountering issues, please provide us with feedback on [our community forum](https://community.sonarsource.com/), which is actively monitored.
