### ISSUE TITLE
add native param for `timeout-minutes` due to github action limitation

### ISSUE THREAD

**Issue by copdips** [SonarSource/sonarqube-quality-gate-action#47]
The example given the readme file shows how to use github action's `timeout-minutes` at job step level, it works. 
However when defining sonar quality gate in an action, and reuse it as composite action, the `timeout-minutes` throws syntax error:
https://github.com/actions/runner/issues/1979
https://github.com/orgs/community/discussions/50481

So could you please implement a timeout inside sonar qualitycheck itself to bypass the limitation. and use it as action input ? And share the default timeout duration ?

PS: the conterpart in azure pipelines has such implementation already with the input `pollingTimeoutSec`: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sonar-qube-publish-v5?view=azure-pipelines

Update:
Does `sonar.qualitygate.timeout` work in `sonar-project.properties`, I set it to `1` for only 1 second, expected the quality gate to be timed out, but it continued the wait for around 10 seconds, and got the results, so it seems that `sonar.qualitygate.timeout` doesn't work.

**Comment by MueChr** [comment]
Created a [PR](https://github.com/SonarSource/sonarqube-quality-gate-action/pull/50) for this feature.

**Comment by jacek-poreda-sonarsource** [comment]
@copdips No, it won't work. The implementation of the Quality Gate Github action is purely done in Bash; it has no interaction with the scanner apart from reading metadata files.

Thanks to @MueChr there is PR opened and I'm looking into it.
