### ISSUE TITLE
The underlying api in this action shows incomplete or wrong results sometimes

### ISSUE THREAD

**Issue by RitikaLaddha** [SonarSource/sonarqube-quality-gate-action#52]
Please take a look at this question I asked on Sonar community, I have all the required screenshots here.
[Link](https://community.sonarsource.com/t/sonar-quality-gate-api-is-showing-wrong-or-incomplete-results-sometimes/112920)

**Comment by jacek-poreda-sonarsource** [comment]
Closing as the topic should continue on Community.
