### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by kumar08401** [SonarSource/sonarqube-quality-gate-action#53]
Hi ,

when i am running github actions pipeline , its faling looks like bug , can someone help me here

#3 DONE 1.3s
  #4 [internal] load .dockerignore
  #4 transferring context: 2B 0.0s done
  #4 DONE 0.1s
  #5 [1/5] FROM docker.io/sonarsource/sonar-scanner-cli:5.0.1@sha256:c[13](https://github.com/kumar08401/drupal/actions/runs/8710882777/job/23893787334#step:2:13)7f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c
  #5 DONE 0.0s
  #6 [internal] load build context
  #6 transferring context: 65B 0.1s done
  #6 DONE 0.1s
  #7 [2/5] COPY entrypoint.sh /entrypoint.sh
  #7 CACHED
  #8 [3/5] RUN chmod +x /entrypoint.sh
  #8 1.200 chmod: /entrypoint.sh: Operation not permitted
  #8 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1

**Comment by nstankov-bg** [comment]
I can confirm the issue is happening too.

It was resolved here?

https://github.com/SonarSource/sonarqube-scan-action/issues/104

**Comment by jacek-poreda-sonarsource** [comment]
This is not the correct repository to raise this issue. If you still have problems please have a look at https://github.com/SonarSource/sonarqube-scan-action
