### ISSUE TITLE
dashboardUrl not really a URL because serverUrl part is missing

### ISSUE THREAD

**Issue by ohommes** [SonarSource/sonarqube-quality-gate-action#54]
When we run and get a scan fail for the quality gate the check-quality-gate.sh always shows:

Detailed information can be found at: ***/dashboard?id=prj-code&pullRequest=4209

So this is non-clickable and everyone complains about that. When we have success at the PR we have a working link in gitea.

When I check check-quality-gate.sh lines 52 and 53 I see:

```
dashboardUrl="$(sed -n 's/dashboardUrl=\(.*\)/\1/p' "${metadataFile}")"
analysisResultMsg="Detailed information can be found at: ${dashboardUrl}\n"
```

Here it never adds the serverUrl properly. Can this be fixed? Can the *** be replaced with a working serverUrl?

**Comment by jacek-poreda-sonarsource** [comment]
Hey, @ohommes

Usually, this may happen when you use same value as secret in github. This is Github security feature to not leak your secrets in logs, could you confirm if you still have an issue once you pull your SQ server URL out from your secrets?

**Comment by ohommes** [comment]
Yes that was it; The URL is now correct. It would be nice if it would be clickable in the future but for now this is good enough!
Thanks for the feedback
